"""
Synthetic Dataset Generation Pipeline.

Orchestrates the end-to-end scenario generation:
- Port infrastructure (ports, berths, cranes, yard zones, routes)
- Vessels, schedules, and container workloads
- Hourly weather and tide observations
- Discrete operational simulation producing hourly feature matrices and future targets
- Strict data leakage prevention
- Multi-factor congestion labels (LOW, MEDIUM, HIGH, CRITICAL)
- Export to clean, standardized CSV files with metadata
"""

import csv
import json
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from generator.environment_generator import (
    generate_tide_observations,
    generate_weather_observations,
)
from generator.port_generator import generate_port_infrastructure
from generator.scenario_config import ScenarioConfig
from generator.vessel_generator import generate_vessels_and_workload
from simulation.random import SimulationRandom


class DatasetGenerationPipeline:
    """End-to-end dataset generator pipeline."""

    def __init__(self, config: ScenarioConfig) -> None:
        self.config = config
        self.rng = SimulationRandom(seed=config.seed)
        self.base_time = datetime(2026, 1, 15, 0, 0, 0, tzinfo=timezone.utc)

    def run(self, output_dir: Path | str) -> dict[str, Any]:
        """Execute the generation pipeline and write CSV files to output_dir."""
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        # 1. Generate Infrastructure
        infra = generate_port_infrastructure(self.rng)
        ports = infra["ports"]
        berths = infra["berths"]
        cranes = infra["cranes"]
        yard_zones = infra["yard_zones"]
        routes = infra["routes"]

        # 2. Generate Vessels, Workloads & Schedules
        vessel_data = generate_vessels_and_workload(
            self.config, berths, yard_zones, self.rng, start_time=self.base_time
        )
        vessels = vessel_data["vessels"]
        schedules = vessel_data["schedules"]
        containers = vessel_data["containers"]

        # 3. Generate Environment (Weather & Tides)
        weather_records = generate_weather_observations(
            self.config.days, self.config.weather_disruption_prob, self.rng, self.base_time
        )
        tide_records = generate_tide_observations(
            self.config.days, self.config.tide_restriction_prob, self.rng, self.base_time
        )

        weather_by_ts = {w["timestamp"]: w for w in weather_records}
        tide_by_ts = {t["timestamp"]: t for t in tide_records}

        # 4. Simulate Operational Timeline
        operational_history, congestion_history = self._simulate_operational_timeline(
            berths=berths,
            cranes=cranes,
            yard_zones=yard_zones,
            vessels=vessels,
            schedules=schedules,
            weather_by_ts=weather_by_ts,
            tide_by_ts=tide_by_ts,
        )

        # 5. Export Datasets to CSV
        self._write_csv(out_path / "ports.csv", ports)
        self._write_csv(out_path / "berths.csv", berths)
        self._write_csv(out_path / "cranes.csv", cranes)
        self._write_csv(out_path / "yard_zones.csv", yard_zones)
        self._write_csv(out_path / "routes.csv", routes)
        self._write_csv(out_path / "vessels.csv", vessels)
        self._write_csv(out_path / "vessel_schedule.csv", schedules)
        self._write_csv(out_path / "containers.csv", containers)
        self._write_csv(out_path / "weather.csv", weather_records)
        self._write_csv(out_path / "tides.csv", tide_records)
        self._write_csv(out_path / "operational_history.csv", operational_history)
        self._write_csv(out_path / "congestion_history.csv", congestion_history)

        # 6. Export Metadata
        metadata = {
            "scenario": self.config.name,
            "seed": self.config.seed,
            "synthetic": True,
            "disclaimer": "Synthetic data generated by HarborAI for simulation and demonstration.",
            "generator_version": "1.0.0",
            "historical_days": self.config.days,
            "total_hours": len(operational_history),
            "vessel_count": len(vessels),
            "container_count": len(containers),
            "schedule_count": len(schedules),
            "primary_target": "future_congestion_risk_6h",
            "target_horizon_hours": self.config.target_horizon_hours,
            "created_at": "2026-01-15T00:00:00Z",  # Deterministic reference timestamp
        }
        with open(out_path / "dataset_metadata.json", "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        return {
            "scenario": self.config.name,
            "output_dir": str(out_path),
            "vessels": len(vessels),
            "containers": len(containers),
            "schedules": len(schedules),
            "operational_rows": len(operational_history),
            "weather_rows": len(weather_records),
            "tide_rows": len(tide_records),
            "congestion_rows": len(congestion_history),
            "metadata": metadata,
        }

    def _simulate_operational_timeline(
        self,
        berths: list[dict[str, Any]],
        cranes: list[dict[str, Any]],
        yard_zones: list[dict[str, Any]],
        vessels: list[dict[str, Any]],
        schedules: list[dict[str, Any]],
        weather_by_ts: dict[str, dict[str, Any]],
        tide_by_ts: dict[str, dict[str, Any]],
    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        """
        Discrete event operational simulation producing historical features and
        future targets without data leakage.
        """
        total_hours = self.config.days * 24
        vessel_map = {v["vessel_id"]: v for v in vessels}

        # Build schedule lookup by arrival datetime
        schedules_by_arrival: list[tuple[datetime, dict[str, Any]]] = []
        for s in schedules:
            dt = datetime.fromisoformat(s["expected_arrival"])
            schedules_by_arrival.append((dt, s))
        schedules_by_arrival.sort(key=lambda x: x[0])

        total_berths = len(berths)
        total_cranes = len(cranes)
        total_yard_capacity = sum(z["total_capacity"] for z in yard_zones)

        # Dynamic state tracking
        occupied_berths = 0
        active_cranes = 0
        queue: list[dict[str, Any]] = []
        berthed_vessels: list[dict[str, Any]] = []
        yard_occupancy = sum(z["occupied_capacity"] for z in yard_zones)
        cumulative_throughput = 0
        waiting_times: list[float] = []

        hourly_states: list[dict[str, Any]] = []

        for h in range(total_hours):
            current_time = self.base_time + timedelta(hours=h)
            current_ts = current_time.isoformat()

            # 1. Check for newly arriving vessels at this hour
            for arr_dt, sched in schedules_by_arrival:
                if current_time <= arr_dt < current_time + timedelta(hours=1):
                    v = vessel_map[sched["vessel_id"]]
                    queue.append(
                        {
                            "vessel_id": v["vessel_id"],
                            "containers": v["containers_to_handle"],
                            "priority": v["priority"],
                            "arrival_time": arr_dt,
                            "waiting_hours": 0.0,
                            "handling_hours": sched["expected_handling_duration_h"],
                            "handling_remaining": sched["expected_handling_duration_h"],
                        }
                    )

            # Weather & tide environmental conditions at time T
            w = weather_by_ts.get(
                current_ts,
                {
                    "temperature_c": 29.0,
                    "wind_speed_knots": 10.0,
                    "precipitation_mm": 0.0,
                    "operational_impact": 0.0,
                },
            )
            t = tide_by_ts.get(
                current_ts,
                {"tide_height_m": 1.8, "tide_state": "rising", "operational_impact": 0.0},
            )

            # Weather slows crane handling slightly if operational_impact > 0
            weather_slowdown = max(0.4, 1.0 - w["operational_impact"] * 0.45)

            # 2. Advance vessels currently at berth
            completed_berthed: list[dict[str, Any]] = []
            for b_vessel in berthed_vessels:
                effective_progress = 1.0 * weather_slowdown
                b_vessel["handling_remaining"] -= effective_progress
                if b_vessel["handling_remaining"] <= 0.0:
                    completed_berthed.append(b_vessel)

            for comp in completed_berthed:
                berthed_vessels.remove(comp)
                occupied_berths = max(0, occupied_berths - 1)
                active_cranes = max(0, active_cranes - 2)
                cumulative_throughput += comp["containers"]
                # Slowly release cargo from yard over time (gate moves out)
                yard_occupancy = max(0, yard_occupancy - int(comp["containers"] * 0.7))

            # 3. Assign berths from queue to available berths
            while queue and occupied_berths < total_berths and active_cranes < total_cranes:
                next_vessel = queue.pop(0)
                occupied_berths += 1
                assigned_crane_count = min(3, total_cranes - active_cranes)
                active_cranes += max(1, assigned_crane_count)
                berthed_vessels.append(next_vessel)
                waiting_times.append(next_vessel["waiting_hours"])

                # Store containers in yard
                available_yard = max(0, total_yard_capacity - yard_occupancy)
                added_containers = min(next_vessel["containers"], available_yard)
                yard_occupancy += added_containers

            # 4. Accrue waiting time for vessels remaining in queue
            for q_vessel in queue:
                q_vessel["waiting_hours"] += 1.0

            # 5. Lookahead scheduled arrivals from schedule (valid future schedule, NOT actual future state)
            scheduled_next_6h = 0
            scheduled_next_12h = 0
            scheduled_next_24h = 0
            containers_next_6h = 0
            containers_next_24h = 0

            for arr_dt, sched in schedules_by_arrival:
                if current_time <= arr_dt < current_time + timedelta(hours=6):
                    scheduled_next_6h += 1
                    containers_next_6h += vessel_map[sched["vessel_id"]]["containers_to_handle"]
                if current_time <= arr_dt < current_time + timedelta(hours=12):
                    scheduled_next_12h += 1
                if current_time <= arr_dt < current_time + timedelta(hours=24):
                    scheduled_next_24h += 1
                    containers_next_24h += vessel_map[sched["vessel_id"]]["containers_to_handle"]

            # Compute current utilization metrics at time T
            b_util = round(occupied_berths / total_berths, 4) if total_berths > 0 else 0.0
            c_util = round(active_cranes / total_cranes, 4) if total_cranes > 0 else 0.0
            y_util = round(yard_occupancy / total_yard_capacity, 4) if total_yard_capacity > 0 else 0.0

            avg_wait = round(sum(waiting_times[-20:]) / max(1, len(waiting_times[-20:])), 2)
            avg_handle = round(
                sum(v["handling_hours"] for v in berthed_vessels) / max(1, len(berthed_vessels)), 2
            )

            high_priority_count = sum(1 for q in queue if q["priority"] in ("high", "critical"))

            # Instantaneous state snapshot at hour h
            hourly_states.append(
                {
                    "timestamp": current_ts,
                    "hour": current_time.hour,
                    "day_of_week": current_time.weekday(),
                    "day_of_month": current_time.day,
                    "month": current_time.month,
                    "is_weekend": 1 if current_time.weekday() >= 5 else 0,
                    "active_vessel_count": len(queue) + len(berthed_vessels),
                    "waiting_vessel_count": len(queue),
                    "queue_length": len(queue),
                    "vessels_at_berth_count": len(berthed_vessels),
                    "occupied_berths": occupied_berths,
                    "available_berths": total_berths - occupied_berths,
                    "berth_utilization": b_util,
                    "active_cranes": active_cranes,
                    "available_cranes": total_cranes - active_cranes,
                    "crane_utilization": c_util,
                    "yard_occupancy": yard_occupancy,
                    "yard_capacity": total_yard_capacity,
                    "yard_utilization": y_util,
                    "average_waiting_time_h": avg_wait,
                    "average_handling_time_h": avg_handle,
                    "high_priority_vessel_count": high_priority_count,
                    "scheduled_arrivals_next_6h": scheduled_next_6h,
                    "scheduled_arrivals_next_12h": scheduled_next_12h,
                    "scheduled_arrivals_next_24h": scheduled_next_24h,
                    "scheduled_incoming_containers_next_6h": containers_next_6h,
                    "scheduled_incoming_containers_next_24h": containers_next_24h,
                    "weather_temperature_c": w["temperature_c"],
                    "weather_wind_speed_knots": w["wind_speed_knots"],
                    "weather_precipitation_mm": w["precipitation_mm"],
                    "weather_operational_impact": w["operational_impact"],
                    "tide_height_m": t["tide_height_m"],
                    "tide_operational_impact": t["operational_impact"],
                    "current_throughput_teu": cumulative_throughput,
                }
            )

        # ---------------------------------------------------------------------
        # Derive Future Target Labels WITHOUT Data Leakage
        # The target evaluates what happens in the future window [T, T + horizon]
        # ---------------------------------------------------------------------
        operational_history: list[dict[str, Any]] = []
        congestion_history: list[dict[str, Any]] = []
        horizon_h = self.config.target_horizon_hours

        for i in range(total_hours):
            state = hourly_states[i]
            current_ts = state["timestamp"]

            # Future window slice: [i, min(total_hours, i + horizon_h)]
            future_slice = hourly_states[i : min(total_hours, i + horizon_h)]
            if not future_slice:
                future_slice = [state]

            # Multi-factor target calculation (emergent from future state)
            future_max_queue = max(s["queue_length"] for s in future_slice)
            future_avg_b_util = sum(s["berth_utilization"] for s in future_slice) / len(future_slice)
            future_avg_c_util = sum(s["crane_utilization"] for s in future_slice) / len(future_slice)
            future_avg_y_util = sum(s["yard_utilization"] for s in future_slice) / len(future_slice)
            future_max_weather_impact = max(s["weather_operational_impact"] for s in future_slice)

            # Composite future pressure index [0.0, 1.0]
            queue_score = min(1.0, future_max_queue / max(1.0, total_berths * 1.5))
            raw_target_index = (
                0.35 * queue_score
                + 0.25 * future_avg_b_util
                + 0.20 * future_avg_c_util
                + 0.15 * future_avg_y_util
                + 0.05 * future_max_weather_impact
            )
            target_score = round(min(1.0, max(0.0, raw_target_index)), 4)

            if target_score < 0.28:
                risk_label = "LOW"
            elif target_score < 0.55:
                risk_label = "MEDIUM"
            elif target_score < 0.80:
                risk_label = "HIGH"
            else:
                risk_label = "CRITICAL"

            # Features row (strictly present and past information)
            feat_row = dict(state)
            feat_row["synthetic"] = True
            operational_history.append(feat_row)

            # Target label row (future prediction horizon)
            target_row = {
                "timestamp": current_ts,
                "target_horizon_h": horizon_h,
                "future_congestion_index_6h": target_score,
                "future_congestion_risk_6h": risk_label,
                "synthetic": True,
            }
            congestion_history.append(target_row)

        return operational_history, congestion_history

    @staticmethod
    def _write_csv(filepath: Path, data: list[dict[str, Any]]) -> None:
        """Helper to write records cleanly to CSV."""
        if not data:
            return
        fieldnames = list(data[0].keys())
        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(data)
